# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'libapp.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1121, 761)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(20)
        MainWindow.setFont(font)
        self.actionMain_menu = QAction(MainWindow)
        self.actionMain_menu.setObjectName(u"actionMain_menu")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.Stack = QStackedWidget(self.centralwidget)
        self.Stack.setObjectName(u"Stack")
        self.home = QWidget()
        self.home.setObjectName(u"home")
        self.gridLayout_5 = QGridLayout(self.home)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.homeLabel1 = QLabel(self.home)
        self.homeLabel1.setObjectName(u"homeLabel1")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.homeLabel1.sizePolicy().hasHeightForWidth())
        self.homeLabel1.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setFamily(u"DejaVu Sans")
        font1.setPointSize(28)
        font1.setBold(True)
        font1.setWeight(75)
        self.homeLabel1.setFont(font1)
        self.homeLabel1.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.verticalLayout.addWidget(self.homeLabel1)

        self.homeLabel2 = QLabel(self.home)
        self.homeLabel2.setObjectName(u"homeLabel2")
        sizePolicy1.setHeightForWidth(self.homeLabel2.sizePolicy().hasHeightForWidth())
        self.homeLabel2.setSizePolicy(sizePolicy1)
        font2 = QFont()
        font2.setPointSize(22)
        self.homeLabel2.setFont(font2)
        self.homeLabel2.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.homeLabel2)


        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.loginLineEdit = QLineEdit(self.home)
        self.loginLineEdit.setObjectName(u"loginLineEdit")
        self.loginLineEdit.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.loginLineEdit.sizePolicy().hasHeightForWidth())
        self.loginLineEdit.setSizePolicy(sizePolicy2)
        font3 = QFont()
        font3.setPointSize(21)
        self.loginLineEdit.setFont(font3)

        self.horizontalLayout_2.addWidget(self.loginLineEdit)

        self.submitLoginButton = QPushButton(self.home)
        self.submitLoginButton.setObjectName(u"submitLoginButton")
        sizePolicy3 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.submitLoginButton.sizePolicy().hasHeightForWidth())
        self.submitLoginButton.setSizePolicy(sizePolicy3)
        self.submitLoginButton.setFont(font2)

        self.horizontalLayout_2.addWidget(self.submitLoginButton)


        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.Stack.addWidget(self.home)
        self.client_home_page = QWidget()
        self.client_home_page.setObjectName(u"client_home_page")
        self.gridLayout_3 = QGridLayout(self.client_home_page)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.helloClientLabel = QLabel(self.client_home_page)
        self.helloClientLabel.setObjectName(u"helloClientLabel")
        sizePolicy1.setHeightForWidth(self.helloClientLabel.sizePolicy().hasHeightForWidth())
        self.helloClientLabel.setSizePolicy(sizePolicy1)
        font4 = QFont()
        font4.setFamily(u"DejaVu Sans")
        font4.setPointSize(29)
        font4.setBold(True)
        font4.setWeight(75)
        self.helloClientLabel.setFont(font4)
        self.helloClientLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.helloClientLabel, 0, 0, 1, 1)

        self.clientHomeWelcomeLabel = QLabel(self.client_home_page)
        self.clientHomeWelcomeLabel.setObjectName(u"clientHomeWelcomeLabel")
        sizePolicy1.setHeightForWidth(self.clientHomeWelcomeLabel.sizePolicy().hasHeightForWidth())
        self.clientHomeWelcomeLabel.setSizePolicy(sizePolicy1)
        font5 = QFont()
        font5.setFamily(u"DejaVu Sans")
        font5.setPointSize(20)
        font5.setBold(True)
        font5.setWeight(75)
        self.clientHomeWelcomeLabel.setFont(font5)
        self.clientHomeWelcomeLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.clientHomeWelcomeLabel, 1, 0, 1, 1)

        self.clientHomeQstLabel = QLabel(self.client_home_page)
        self.clientHomeQstLabel.setObjectName(u"clientHomeQstLabel")
        sizePolicy.setHeightForWidth(self.clientHomeQstLabel.sizePolicy().hasHeightForWidth())
        self.clientHomeQstLabel.setSizePolicy(sizePolicy)
        self.clientHomeQstLabel.setFont(font5)
        self.clientHomeQstLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.clientHomeQstLabel, 3, 0, 1, 1)

        self.clientModeLabel = QLabel(self.client_home_page)
        self.clientModeLabel.setObjectName(u"clientModeLabel")
        sizePolicy1.setHeightForWidth(self.clientModeLabel.sizePolicy().hasHeightForWidth())
        self.clientModeLabel.setSizePolicy(sizePolicy1)
        font6 = QFont()
        font6.setFamily(u"DejaVu Sans")
        font6.setBold(True)
        font6.setWeight(75)
        self.clientModeLabel.setFont(font6)
        self.clientModeLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.clientModeLabel, 2, 0, 1, 1)


        self.verticalLayout_4.addLayout(self.gridLayout)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.clientDisplayRentingsButton = QPushButton(self.client_home_page)
        self.clientDisplayRentingsButton.setObjectName(u"clientDisplayRentingsButton")
        sizePolicy4 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.MinimumExpanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.clientDisplayRentingsButton.sizePolicy().hasHeightForWidth())
        self.clientDisplayRentingsButton.setSizePolicy(sizePolicy4)
        font7 = QFont()
        font7.setFamily(u"DejaVu Sans")
        font7.setPointSize(20)
        font7.setBold(False)
        font7.setWeight(50)
        self.clientDisplayRentingsButton.setFont(font7)

        self.gridLayout_2.addWidget(self.clientDisplayRentingsButton, 2, 0, 1, 1)

        self.clientDisplayHistoryButton = QPushButton(self.client_home_page)
        self.clientDisplayHistoryButton.setObjectName(u"clientDisplayHistoryButton")
        sizePolicy4.setHeightForWidth(self.clientDisplayHistoryButton.sizePolicy().hasHeightForWidth())
        self.clientDisplayHistoryButton.setSizePolicy(sizePolicy4)
        self.clientDisplayHistoryButton.setFont(font7)

        self.gridLayout_2.addWidget(self.clientDisplayHistoryButton, 4, 0, 1, 1)

        self.clientLogoutButton = QPushButton(self.client_home_page)
        self.clientLogoutButton.setObjectName(u"clientLogoutButton")
        sizePolicy4.setHeightForWidth(self.clientLogoutButton.sizePolicy().hasHeightForWidth())
        self.clientLogoutButton.setSizePolicy(sizePolicy4)
        self.clientLogoutButton.setFont(font7)

        self.gridLayout_2.addWidget(self.clientLogoutButton, 5, 0, 1, 1)

        self.clientDisplayBooksButton = QPushButton(self.client_home_page)
        self.clientDisplayBooksButton.setObjectName(u"clientDisplayBooksButton")
        sizePolicy4.setHeightForWidth(self.clientDisplayBooksButton.sizePolicy().hasHeightForWidth())
        self.clientDisplayBooksButton.setSizePolicy(sizePolicy4)
        self.clientDisplayBooksButton.setFont(font7)

        self.gridLayout_2.addWidget(self.clientDisplayBooksButton, 0, 0, 1, 1)

        self.clientDisplayReservationsButton = QPushButton(self.client_home_page)
        self.clientDisplayReservationsButton.setObjectName(u"clientDisplayReservationsButton")
        sizePolicy4.setHeightForWidth(self.clientDisplayReservationsButton.sizePolicy().hasHeightForWidth())
        self.clientDisplayReservationsButton.setSizePolicy(sizePolicy4)
        font8 = QFont()
        font8.setFamily(u"DejaVu Sans")
        self.clientDisplayReservationsButton.setFont(font8)

        self.gridLayout_2.addWidget(self.clientDisplayReservationsButton, 3, 0, 1, 1)


        self.verticalLayout_4.addLayout(self.gridLayout_2)


        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.Stack.addWidget(self.client_home_page)
        self.client_display_books_page = QWidget()
        self.client_display_books_page.setObjectName(u"client_display_books_page")
        self.verticalLayout_20 = QVBoxLayout(self.client_display_books_page)
        self.verticalLayout_20.setObjectName(u"verticalLayout_20")
        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.mainMenuButton0 = QPushButton(self.client_display_books_page)
        self.mainMenuButton0.setObjectName(u"mainMenuButton0")
        sizePolicy5 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Maximum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.mainMenuButton0.sizePolicy().hasHeightForWidth())
        self.mainMenuButton0.setSizePolicy(sizePolicy5)
        font9 = QFont()
        font9.setFamily(u"DejaVu Sans")
        font9.setPointSize(21)
        font9.setBold(True)
        font9.setWeight(75)
        self.mainMenuButton0.setFont(font9)

        self.verticalLayout_5.addWidget(self.mainMenuButton0)

        self.splitter = QSplitter(self.client_display_books_page)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.listOfGenres = QListWidget(self.splitter)
        self.listOfGenres.setObjectName(u"listOfGenres")
        sizePolicy6 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.listOfGenres.sizePolicy().hasHeightForWidth())
        self.listOfGenres.setSizePolicy(sizePolicy6)
        font10 = QFont()
        font10.setFamily(u"DejaVu Sans")
        font10.setPointSize(17)
        self.listOfGenres.setFont(font10)
        self.splitter.addWidget(self.listOfGenres)
        self.genreStack = QStackedWidget(self.splitter)
        self.genreStack.setObjectName(u"genreStack")
        sizePolicy7 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.genreStack.sizePolicy().hasHeightForWidth())
        self.genreStack.setSizePolicy(sizePolicy7)
        self.book_info_page = QWidget()
        self.book_info_page.setObjectName(u"book_info_page")
        self.verticalLayout_6 = QVBoxLayout(self.book_info_page)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.splitter_3 = QSplitter(self.book_info_page)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Vertical)
        self.listOfBooks = QListWidget(self.splitter_3)
        self.listOfBooks.setObjectName(u"listOfBooks")
        sizePolicy8 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Maximum)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.listOfBooks.sizePolicy().hasHeightForWidth())
        self.listOfBooks.setSizePolicy(sizePolicy8)
        self.listOfBooks.setFont(font10)
        self.splitter_3.addWidget(self.listOfBooks)
        self.bookStack = QStackedWidget(self.splitter_3)
        self.bookStack.setObjectName(u"bookStack")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.verticalLayout_7 = QVBoxLayout(self.page_3)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.chooseBookLabel = QLabel(self.page_3)
        self.chooseBookLabel.setObjectName(u"chooseBookLabel")
        self.chooseBookLabel.setFont(font9)
        self.chooseBookLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_7.addWidget(self.chooseBookLabel)

        self.bookStack.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.verticalLayout_3 = QVBoxLayout(self.page_4)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.bookInfo = QLabel(self.page_4)
        self.bookInfo.setObjectName(u"bookInfo")
        sizePolicy1.setHeightForWidth(self.bookInfo.sizePolicy().hasHeightForWidth())
        self.bookInfo.setSizePolicy(sizePolicy1)
        font11 = QFont()
        font11.setFamily(u"DejaVu Sans")
        font11.setPointSize(15)
        font11.setBold(True)
        font11.setWeight(75)
        self.bookInfo.setFont(font11)
        self.bookInfo.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.verticalLayout_3.addWidget(self.bookInfo)

        self.bookBorrowButton = QPushButton(self.page_4)
        self.bookBorrowButton.setObjectName(u"bookBorrowButton")
        sizePolicy9 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.bookBorrowButton.sizePolicy().hasHeightForWidth())
        self.bookBorrowButton.setSizePolicy(sizePolicy9)
        font12 = QFont()
        font12.setFamily(u"DejaVu Sans")
        font12.setPointSize(15)
        self.bookBorrowButton.setFont(font12)

        self.verticalLayout_3.addWidget(self.bookBorrowButton)

        self.reservationButton = QPushButton(self.page_4)
        self.reservationButton.setObjectName(u"reservationButton")
        sizePolicy9.setHeightForWidth(self.reservationButton.sizePolicy().hasHeightForWidth())
        self.reservationButton.setSizePolicy(sizePolicy9)
        self.reservationButton.setFont(font12)

        self.verticalLayout_3.addWidget(self.reservationButton)

        self.bookStack.addWidget(self.page_4)
        self.splitter_3.addWidget(self.bookStack)

        self.verticalLayout_6.addWidget(self.splitter_3)

        self.genreStack.addWidget(self.book_info_page)
        self.book_home_page = QWidget()
        self.book_home_page.setObjectName(u"book_home_page")
        self.gridLayout_4 = QGridLayout(self.book_home_page)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.chooseGenreLabel = QLabel(self.book_home_page)
        self.chooseGenreLabel.setObjectName(u"chooseGenreLabel")
        self.chooseGenreLabel.setFont(font9)
        self.chooseGenreLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.chooseGenreLabel, 0, 0, 1, 1)

        self.genreStack.addWidget(self.book_home_page)
        self.splitter.addWidget(self.genreStack)

        self.verticalLayout_5.addWidget(self.splitter)


        self.verticalLayout_20.addLayout(self.verticalLayout_5)

        self.Stack.addWidget(self.client_display_books_page)
        self.client_display_rentings_page = QWidget()
        self.client_display_rentings_page.setObjectName(u"client_display_rentings_page")
        self.verticalLayout_8 = QVBoxLayout(self.client_display_rentings_page)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.mainMenuButton1 = QPushButton(self.client_display_rentings_page)
        self.mainMenuButton1.setObjectName(u"mainMenuButton1")
        self.mainMenuButton1.setFont(font9)

        self.verticalLayout_2.addWidget(self.mainMenuButton1)

        self.ifClientHasRentingStack = QStackedWidget(self.client_display_rentings_page)
        self.ifClientHasRentingStack.setObjectName(u"ifClientHasRentingStack")
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.verticalLayout_18 = QVBoxLayout(self.page_9)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.splitter_2 = QSplitter(self.page_9)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.listOfCurrentRentings = QListWidget(self.splitter_2)
        self.listOfCurrentRentings.setObjectName(u"listOfCurrentRentings")
        self.splitter_2.addWidget(self.listOfCurrentRentings)
        self.curRentingStack = QStackedWidget(self.splitter_2)
        self.curRentingStack.setObjectName(u"curRentingStack")
        sizePolicy10 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy10.setHorizontalStretch(0)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.curRentingStack.sizePolicy().hasHeightForWidth())
        self.curRentingStack.setSizePolicy(sizePolicy10)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.verticalLayout_9 = QVBoxLayout(self.page)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.chooseRentingLabel = QLabel(self.page)
        self.chooseRentingLabel.setObjectName(u"chooseRentingLabel")
        self.chooseRentingLabel.setFont(font9)
        self.chooseRentingLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_9.addWidget(self.chooseRentingLabel)

        self.curRentingStack.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.verticalLayout_11 = QVBoxLayout(self.page_2)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_10 = QVBoxLayout()
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.rentingBookInfo = QLabel(self.page_2)
        self.rentingBookInfo.setObjectName(u"rentingBookInfo")
        sizePolicy11 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        sizePolicy11.setHorizontalStretch(0)
        sizePolicy11.setVerticalStretch(0)
        sizePolicy11.setHeightForWidth(self.rentingBookInfo.sizePolicy().hasHeightForWidth())
        self.rentingBookInfo.setSizePolicy(sizePolicy11)
        font13 = QFont()
        font13.setFamily(u"DejaVu Sans")
        font13.setPointSize(16)
        font13.setBold(True)
        font13.setWeight(75)
        self.rentingBookInfo.setFont(font13)

        self.verticalLayout_10.addWidget(self.rentingBookInfo)

        self.rentingInfo = QLabel(self.page_2)
        self.rentingInfo.setObjectName(u"rentingInfo")
        self.rentingInfo.setFont(font13)
        self.rentingInfo.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.verticalLayout_10.addWidget(self.rentingInfo)

        self.returnBookButton = QPushButton(self.page_2)
        self.returnBookButton.setObjectName(u"returnBookButton")
        self.returnBookButton.setFont(font12)

        self.verticalLayout_10.addWidget(self.returnBookButton)

        self.renewRentingButton = QPushButton(self.page_2)
        self.renewRentingButton.setObjectName(u"renewRentingButton")
        self.renewRentingButton.setFont(font12)

        self.verticalLayout_10.addWidget(self.renewRentingButton)


        self.verticalLayout_11.addLayout(self.verticalLayout_10)

        self.curRentingStack.addWidget(self.page_2)
        self.splitter_2.addWidget(self.curRentingStack)

        self.verticalLayout_18.addWidget(self.splitter_2)

        self.ifClientHasRentingStack.addWidget(self.page_9)
        self.page_10 = QWidget()
        self.page_10.setObjectName(u"page_10")
        self.verticalLayout_19 = QVBoxLayout(self.page_10)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.noCurrentRentingsLabel = QLabel(self.page_10)
        self.noCurrentRentingsLabel.setObjectName(u"noCurrentRentingsLabel")
        self.noCurrentRentingsLabel.setFont(font1)
        self.noCurrentRentingsLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_19.addWidget(self.noCurrentRentingsLabel)

        self.ifClientHasRentingStack.addWidget(self.page_10)

        self.verticalLayout_2.addWidget(self.ifClientHasRentingStack)


        self.verticalLayout_8.addLayout(self.verticalLayout_2)

        self.Stack.addWidget(self.client_display_rentings_page)
        self.client_display_history_page = QWidget()
        self.client_display_history_page.setObjectName(u"client_display_history_page")
        self.verticalLayout_14 = QVBoxLayout(self.client_display_history_page)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_13 = QVBoxLayout()
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.mainMenuButton2 = QPushButton(self.client_display_history_page)
        self.mainMenuButton2.setObjectName(u"mainMenuButton2")
        self.mainMenuButton2.setFont(font9)

        self.verticalLayout_13.addWidget(self.mainMenuButton2)

        self.splitter_4 = QSplitter(self.client_display_history_page)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setOrientation(Qt.Horizontal)
        self.rentingHistoryCalendar = QCalendarWidget(self.splitter_4)
        self.rentingHistoryCalendar.setObjectName(u"rentingHistoryCalendar")
        sizePolicy12 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy12.setHorizontalStretch(0)
        sizePolicy12.setVerticalStretch(0)
        sizePolicy12.setHeightForWidth(self.rentingHistoryCalendar.sizePolicy().hasHeightForWidth())
        self.rentingHistoryCalendar.setSizePolicy(sizePolicy12)
        self.rentingHistoryCalendar.setFont(font6)
        self.splitter_4.addWidget(self.rentingHistoryCalendar)
        self.calendarStack = QStackedWidget(self.splitter_4)
        self.calendarStack.setObjectName(u"calendarStack")
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.verticalLayout_12 = QVBoxLayout(self.page_5)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.selectDayLabel = QLabel(self.page_5)
        self.selectDayLabel.setObjectName(u"selectDayLabel")
        sizePolicy13 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.MinimumExpanding)
        sizePolicy13.setHorizontalStretch(0)
        sizePolicy13.setVerticalStretch(0)
        sizePolicy13.setHeightForWidth(self.selectDayLabel.sizePolicy().hasHeightForWidth())
        self.selectDayLabel.setSizePolicy(sizePolicy13)
        self.selectDayLabel.setFont(font9)
        self.selectDayLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_12.addWidget(self.selectDayLabel)

        self.calendarStack.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.verticalLayout_16 = QVBoxLayout(self.page_6)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.splitter_5 = QSplitter(self.page_6)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setOrientation(Qt.Vertical)
        self.listOfRentingsHistory = QListWidget(self.splitter_5)
        self.listOfRentingsHistory.setObjectName(u"listOfRentingsHistory")
        sizePolicy8.setHeightForWidth(self.listOfRentingsHistory.sizePolicy().hasHeightForWidth())
        self.listOfRentingsHistory.setSizePolicy(sizePolicy8)
        self.splitter_5.addWidget(self.listOfRentingsHistory)
        self.rentingHistoryStack = QStackedWidget(self.splitter_5)
        self.rentingHistoryStack.setObjectName(u"rentingHistoryStack")
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.verticalLayout_15 = QVBoxLayout(self.page_7)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.rentingHistoryChooseRenting = QLabel(self.page_7)
        self.rentingHistoryChooseRenting.setObjectName(u"rentingHistoryChooseRenting")
        self.rentingHistoryChooseRenting.setFont(font13)
        self.rentingHistoryChooseRenting.setAlignment(Qt.AlignCenter)

        self.verticalLayout_15.addWidget(self.rentingHistoryChooseRenting)

        self.rentingHistoryStack.addWidget(self.page_7)
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.verticalLayout_17 = QVBoxLayout(self.page_8)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.rentingHistoryRentingInfo = QLabel(self.page_8)
        self.rentingHistoryRentingInfo.setObjectName(u"rentingHistoryRentingInfo")
        sizePolicy.setHeightForWidth(self.rentingHistoryRentingInfo.sizePolicy().hasHeightForWidth())
        self.rentingHistoryRentingInfo.setSizePolicy(sizePolicy)
        self.rentingHistoryRentingInfo.setFont(font13)
        self.rentingHistoryRentingInfo.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.verticalLayout_17.addWidget(self.rentingHistoryRentingInfo)

        self.rentingHistoryStack.addWidget(self.page_8)
        self.splitter_5.addWidget(self.rentingHistoryStack)

        self.verticalLayout_16.addWidget(self.splitter_5)

        self.calendarStack.addWidget(self.page_6)
        self.splitter_4.addWidget(self.calendarStack)

        self.verticalLayout_13.addWidget(self.splitter_4)


        self.verticalLayout_14.addLayout(self.verticalLayout_13)

        self.Stack.addWidget(self.client_display_history_page)
        self.client_display_reservations_page = QWidget()
        self.client_display_reservations_page.setObjectName(u"client_display_reservations_page")
        self.gridLayout_6 = QGridLayout(self.client_display_reservations_page)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.verticalLayout_21 = QVBoxLayout()
        self.verticalLayout_21.setObjectName(u"verticalLayout_21")
        self.mainMenuButton3 = QPushButton(self.client_display_reservations_page)
        self.mainMenuButton3.setObjectName(u"mainMenuButton3")
        self.mainMenuButton3.setFont(font9)

        self.verticalLayout_21.addWidget(self.mainMenuButton3)

        self.ifClientHasNoReservationsStack = QStackedWidget(self.client_display_reservations_page)
        self.ifClientHasNoReservationsStack.setObjectName(u"ifClientHasNoReservationsStack")
        self.page_11 = QWidget()
        self.page_11.setObjectName(u"page_11")
        self.gridLayout_7 = QGridLayout(self.page_11)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.splitter_6 = QSplitter(self.page_11)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setOrientation(Qt.Horizontal)
        self.listOfReservations = QListWidget(self.splitter_6)
        self.listOfReservations.setObjectName(u"listOfReservations")
        self.splitter_6.addWidget(self.listOfReservations)
        self.reservationStack = QStackedWidget(self.splitter_6)
        self.reservationStack.setObjectName(u"reservationStack")
        sizePolicy10.setHeightForWidth(self.reservationStack.sizePolicy().hasHeightForWidth())
        self.reservationStack.setSizePolicy(sizePolicy10)
        self.page_13 = QWidget()
        self.page_13.setObjectName(u"page_13")
        self.gridLayout_8 = QGridLayout(self.page_13)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.chooseReservationLabel = QLabel(self.page_13)
        self.chooseReservationLabel.setObjectName(u"chooseReservationLabel")
        self.chooseReservationLabel.setFont(font9)
        self.chooseReservationLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.chooseReservationLabel, 0, 0, 1, 1)

        self.reservationStack.addWidget(self.page_13)
        self.page_14 = QWidget()
        self.page_14.setObjectName(u"page_14")
        self.gridLayout_9 = QGridLayout(self.page_14)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.verticalLayout_23 = QVBoxLayout()
        self.verticalLayout_23.setObjectName(u"verticalLayout_23")
        self.reservationInfo = QLabel(self.page_14)
        self.reservationInfo.setObjectName(u"reservationInfo")
        sizePolicy12.setHeightForWidth(self.reservationInfo.sizePolicy().hasHeightForWidth())
        self.reservationInfo.setSizePolicy(sizePolicy12)
        self.reservationInfo.setFont(font13)
        self.reservationInfo.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.verticalLayout_23.addWidget(self.reservationInfo)

        self.reservationBorrowButton = QPushButton(self.page_14)
        self.reservationBorrowButton.setObjectName(u"reservationBorrowButton")
        sizePolicy5.setHeightForWidth(self.reservationBorrowButton.sizePolicy().hasHeightForWidth())
        self.reservationBorrowButton.setSizePolicy(sizePolicy5)
        self.reservationBorrowButton.setFont(font8)

        self.verticalLayout_23.addWidget(self.reservationBorrowButton)

        self.cancelReservationButton = QPushButton(self.page_14)
        self.cancelReservationButton.setObjectName(u"cancelReservationButton")
        sizePolicy5.setHeightForWidth(self.cancelReservationButton.sizePolicy().hasHeightForWidth())
        self.cancelReservationButton.setSizePolicy(sizePolicy5)
        font14 = QFont()
        font14.setFamily(u"DejaVu Sans")
        font14.setPointSize(20)
        self.cancelReservationButton.setFont(font14)

        self.verticalLayout_23.addWidget(self.cancelReservationButton)


        self.gridLayout_9.addLayout(self.verticalLayout_23, 0, 0, 1, 1)

        self.reservationStack.addWidget(self.page_14)
        self.splitter_6.addWidget(self.reservationStack)

        self.gridLayout_7.addWidget(self.splitter_6, 0, 0, 1, 1)

        self.ifClientHasNoReservationsStack.addWidget(self.page_11)
        self.page_12 = QWidget()
        self.page_12.setObjectName(u"page_12")
        self.verticalLayout_22 = QVBoxLayout(self.page_12)
        self.verticalLayout_22.setObjectName(u"verticalLayout_22")
        self.noCurrentReservationsLabel = QLabel(self.page_12)
        self.noCurrentReservationsLabel.setObjectName(u"noCurrentReservationsLabel")
        self.noCurrentReservationsLabel.setFont(font1)
        self.noCurrentReservationsLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_22.addWidget(self.noCurrentReservationsLabel)

        self.ifClientHasNoReservationsStack.addWidget(self.page_12)

        self.verticalLayout_21.addWidget(self.ifClientHasNoReservationsStack)


        self.gridLayout_6.addLayout(self.verticalLayout_21, 0, 0, 1, 1)

        self.Stack.addWidget(self.client_display_reservations_page)
        self.librarian_home_page = QWidget()
        self.librarian_home_page.setObjectName(u"librarian_home_page")
        self.gridLayout_12 = QGridLayout(self.librarian_home_page)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.verticalLayout_24 = QVBoxLayout()
        self.verticalLayout_24.setObjectName(u"verticalLayout_24")
        self.gridLayout_11 = QGridLayout()
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.librarianHelloLabel = QLabel(self.librarian_home_page)
        self.librarianHelloLabel.setObjectName(u"librarianHelloLabel")
        sizePolicy1.setHeightForWidth(self.librarianHelloLabel.sizePolicy().hasHeightForWidth())
        self.librarianHelloLabel.setSizePolicy(sizePolicy1)
        font15 = QFont()
        font15.setFamily(u"DejaVu Sans")
        font15.setPointSize(32)
        font15.setBold(True)
        font15.setWeight(75)
        self.librarianHelloLabel.setFont(font15)
        self.librarianHelloLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout_11.addWidget(self.librarianHelloLabel, 0, 0, 1, 1)

        self.librarianWelcomeLabel = QLabel(self.librarian_home_page)
        self.librarianWelcomeLabel.setObjectName(u"librarianWelcomeLabel")
        sizePolicy1.setHeightForWidth(self.librarianWelcomeLabel.sizePolicy().hasHeightForWidth())
        self.librarianWelcomeLabel.setSizePolicy(sizePolicy1)
        self.librarianWelcomeLabel.setFont(font9)
        self.librarianWelcomeLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout_11.addWidget(self.librarianWelcomeLabel, 1, 0, 1, 1)

        self.librarianQstLabel = QLabel(self.librarian_home_page)
        self.librarianQstLabel.setObjectName(u"librarianQstLabel")
        sizePolicy.setHeightForWidth(self.librarianQstLabel.sizePolicy().hasHeightForWidth())
        self.librarianQstLabel.setSizePolicy(sizePolicy)
        self.librarianQstLabel.setFont(font5)
        self.librarianQstLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout_11.addWidget(self.librarianQstLabel, 3, 0, 1, 1)

        self.librarianModeLabel = QLabel(self.librarian_home_page)
        self.librarianModeLabel.setObjectName(u"librarianModeLabel")
        sizePolicy1.setHeightForWidth(self.librarianModeLabel.sizePolicy().hasHeightForWidth())
        self.librarianModeLabel.setSizePolicy(sizePolicy1)
        self.librarianModeLabel.setFont(font6)
        self.librarianModeLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout_11.addWidget(self.librarianModeLabel, 2, 0, 1, 1)


        self.verticalLayout_24.addLayout(self.gridLayout_11)

        self.gridLayout_10 = QGridLayout()
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.librarianAddBookButton = QPushButton(self.librarian_home_page)
        self.librarianAddBookButton.setObjectName(u"librarianAddBookButton")
        sizePolicy4.setHeightForWidth(self.librarianAddBookButton.sizePolicy().hasHeightForWidth())
        self.librarianAddBookButton.setSizePolicy(sizePolicy4)
        self.librarianAddBookButton.setFont(font8)

        self.gridLayout_10.addWidget(self.librarianAddBookButton, 0, 0, 1, 1)

        self.librarianRemoveBookButton = QPushButton(self.librarian_home_page)
        self.librarianRemoveBookButton.setObjectName(u"librarianRemoveBookButton")
        sizePolicy4.setHeightForWidth(self.librarianRemoveBookButton.sizePolicy().hasHeightForWidth())
        self.librarianRemoveBookButton.setSizePolicy(sizePolicy4)
        self.librarianRemoveBookButton.setFont(font8)

        self.gridLayout_10.addWidget(self.librarianRemoveBookButton, 1, 0, 1, 1)

        self.librarianAddMemberButton = QPushButton(self.librarian_home_page)
        self.librarianAddMemberButton.setObjectName(u"librarianAddMemberButton")
        sizePolicy4.setHeightForWidth(self.librarianAddMemberButton.sizePolicy().hasHeightForWidth())
        self.librarianAddMemberButton.setSizePolicy(sizePolicy4)
        self.librarianAddMemberButton.setFont(font8)

        self.gridLayout_10.addWidget(self.librarianAddMemberButton, 2, 0, 1, 1)

        self.librarianDisplayMembersButton = QPushButton(self.librarian_home_page)
        self.librarianDisplayMembersButton.setObjectName(u"librarianDisplayMembersButton")
        sizePolicy4.setHeightForWidth(self.librarianDisplayMembersButton.sizePolicy().hasHeightForWidth())
        self.librarianDisplayMembersButton.setSizePolicy(sizePolicy4)
        self.librarianDisplayMembersButton.setFont(font8)

        self.gridLayout_10.addWidget(self.librarianDisplayMembersButton, 3, 0, 1, 1)

        self.librarianDisplayRentingsInfoButton = QPushButton(self.librarian_home_page)
        self.librarianDisplayRentingsInfoButton.setObjectName(u"librarianDisplayRentingsInfoButton")
        sizePolicy4.setHeightForWidth(self.librarianDisplayRentingsInfoButton.sizePolicy().hasHeightForWidth())
        self.librarianDisplayRentingsInfoButton.setSizePolicy(sizePolicy4)
        self.librarianDisplayRentingsInfoButton.setFont(font8)

        self.gridLayout_10.addWidget(self.librarianDisplayRentingsInfoButton, 4, 0, 1, 1)

        self.librarianLogoutButton = QPushButton(self.librarian_home_page)
        self.librarianLogoutButton.setObjectName(u"librarianLogoutButton")
        sizePolicy4.setHeightForWidth(self.librarianLogoutButton.sizePolicy().hasHeightForWidth())
        self.librarianLogoutButton.setSizePolicy(sizePolicy4)
        self.librarianLogoutButton.setFont(font8)

        self.gridLayout_10.addWidget(self.librarianLogoutButton, 5, 0, 1, 1)


        self.verticalLayout_24.addLayout(self.gridLayout_10)


        self.gridLayout_12.addLayout(self.verticalLayout_24, 0, 0, 1, 1)

        self.Stack.addWidget(self.librarian_home_page)
        self.librarian_add_book_page = QWidget()
        self.librarian_add_book_page.setObjectName(u"librarian_add_book_page")
        self.gridLayout_13 = QGridLayout(self.librarian_add_book_page)
        self.gridLayout_13.setObjectName(u"gridLayout_13")
        self.verticalLayout_25 = QVBoxLayout()
        self.verticalLayout_25.setObjectName(u"verticalLayout_25")
        self.mainMenuButton4 = QPushButton(self.librarian_add_book_page)
        self.mainMenuButton4.setObjectName(u"mainMenuButton4")
        self.mainMenuButton4.setFont(font9)

        self.verticalLayout_25.addWidget(self.mainMenuButton4)

        self.addBookTitleLabel = QLabel(self.librarian_add_book_page)
        self.addBookTitleLabel.setObjectName(u"addBookTitleLabel")
        sizePolicy11.setHeightForWidth(self.addBookTitleLabel.sizePolicy().hasHeightForWidth())
        self.addBookTitleLabel.setSizePolicy(sizePolicy11)
        self.addBookTitleLabel.setFont(font8)
        self.addBookTitleLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_25.addWidget(self.addBookTitleLabel)

        self.addBookTitleLineEdit = QLineEdit(self.librarian_add_book_page)
        self.addBookTitleLineEdit.setObjectName(u"addBookTitleLineEdit")
        sizePolicy8.setHeightForWidth(self.addBookTitleLineEdit.sizePolicy().hasHeightForWidth())
        self.addBookTitleLineEdit.setSizePolicy(sizePolicy8)
        self.addBookTitleLineEdit.setFont(font8)

        self.verticalLayout_25.addWidget(self.addBookTitleLineEdit)

        self.addBookAuthorsLabel = QLabel(self.librarian_add_book_page)
        self.addBookAuthorsLabel.setObjectName(u"addBookAuthorsLabel")
        sizePolicy11.setHeightForWidth(self.addBookAuthorsLabel.sizePolicy().hasHeightForWidth())
        self.addBookAuthorsLabel.setSizePolicy(sizePolicy11)
        self.addBookAuthorsLabel.setFont(font8)
        self.addBookAuthorsLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_25.addWidget(self.addBookAuthorsLabel)

        self.addBookAuthorsLineEdit = QLineEdit(self.librarian_add_book_page)
        self.addBookAuthorsLineEdit.setObjectName(u"addBookAuthorsLineEdit")
        sizePolicy8.setHeightForWidth(self.addBookAuthorsLineEdit.sizePolicy().hasHeightForWidth())
        self.addBookAuthorsLineEdit.setSizePolicy(sizePolicy8)
        self.addBookAuthorsLineEdit.setFont(font8)

        self.verticalLayout_25.addWidget(self.addBookAuthorsLineEdit)

        self.addBookGenreLabel = QLabel(self.librarian_add_book_page)
        self.addBookGenreLabel.setObjectName(u"addBookGenreLabel")
        sizePolicy11.setHeightForWidth(self.addBookGenreLabel.sizePolicy().hasHeightForWidth())
        self.addBookGenreLabel.setSizePolicy(sizePolicy11)
        self.addBookGenreLabel.setFont(font8)
        self.addBookGenreLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_25.addWidget(self.addBookGenreLabel)

        self.addBookGenreLineEdit = QLineEdit(self.librarian_add_book_page)
        self.addBookGenreLineEdit.setObjectName(u"addBookGenreLineEdit")
        sizePolicy8.setHeightForWidth(self.addBookGenreLineEdit.sizePolicy().hasHeightForWidth())
        self.addBookGenreLineEdit.setSizePolicy(sizePolicy8)
        self.addBookGenreLineEdit.setFont(font8)

        self.verticalLayout_25.addWidget(self.addBookGenreLineEdit)

        self.addBookIdLabel = QLabel(self.librarian_add_book_page)
        self.addBookIdLabel.setObjectName(u"addBookIdLabel")
        sizePolicy11.setHeightForWidth(self.addBookIdLabel.sizePolicy().hasHeightForWidth())
        self.addBookIdLabel.setSizePolicy(sizePolicy11)
        self.addBookIdLabel.setFont(font8)
        self.addBookIdLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_25.addWidget(self.addBookIdLabel)

        self.addBookIdLineEdit = QLineEdit(self.librarian_add_book_page)
        self.addBookIdLineEdit.setObjectName(u"addBookIdLineEdit")
        sizePolicy8.setHeightForWidth(self.addBookIdLineEdit.sizePolicy().hasHeightForWidth())
        self.addBookIdLineEdit.setSizePolicy(sizePolicy8)
        self.addBookIdLineEdit.setFont(font8)

        self.verticalLayout_25.addWidget(self.addBookIdLineEdit)

        self.addBookButton = QPushButton(self.librarian_add_book_page)
        self.addBookButton.setObjectName(u"addBookButton")
        sizePolicy5.setHeightForWidth(self.addBookButton.sizePolicy().hasHeightForWidth())
        self.addBookButton.setSizePolicy(sizePolicy5)
        self.addBookButton.setFont(font6)

        self.verticalLayout_25.addWidget(self.addBookButton)


        self.gridLayout_13.addLayout(self.verticalLayout_25, 0, 0, 1, 1)

        self.Stack.addWidget(self.librarian_add_book_page)
        self.librarian_remove_book_page = QWidget()
        self.librarian_remove_book_page.setObjectName(u"librarian_remove_book_page")
        self.verticalLayout_27 = QVBoxLayout(self.librarian_remove_book_page)
        self.verticalLayout_27.setObjectName(u"verticalLayout_27")
        self.verticalLayout_26 = QVBoxLayout()
        self.verticalLayout_26.setObjectName(u"verticalLayout_26")
        self.mainMenuButton5 = QPushButton(self.librarian_remove_book_page)
        self.mainMenuButton5.setObjectName(u"mainMenuButton5")
        self.mainMenuButton5.setFont(font6)

        self.verticalLayout_26.addWidget(self.mainMenuButton5)

        self.checkIfBooksInLibraryStack = QStackedWidget(self.librarian_remove_book_page)
        self.checkIfBooksInLibraryStack.setObjectName(u"checkIfBooksInLibraryStack")
        self.page_15 = QWidget()
        self.page_15.setObjectName(u"page_15")
        self.verticalLayout_28 = QVBoxLayout(self.page_15)
        self.verticalLayout_28.setObjectName(u"verticalLayout_28")
        self.checkIfBookInLibraryLabel = QLabel(self.page_15)
        self.checkIfBookInLibraryLabel.setObjectName(u"checkIfBookInLibraryLabel")
        font16 = QFont()
        font16.setFamily(u"DejaVu Sans")
        font16.setPointSize(22)
        font16.setBold(True)
        font16.setWeight(75)
        self.checkIfBookInLibraryLabel.setFont(font16)
        self.checkIfBookInLibraryLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_28.addWidget(self.checkIfBookInLibraryLabel)

        self.checkIfBooksInLibraryStack.addWidget(self.page_15)
        self.page_16 = QWidget()
        self.page_16.setObjectName(u"page_16")
        self.horizontalLayout_3 = QHBoxLayout(self.page_16)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.splitter_7 = QSplitter(self.page_16)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setOrientation(Qt.Horizontal)
        self.removalListOfBooks = QListWidget(self.splitter_7)
        self.removalListOfBooks.setObjectName(u"removalListOfBooks")
        self.splitter_7.addWidget(self.removalListOfBooks)
        self.bookRemovalStack = QStackedWidget(self.splitter_7)
        self.bookRemovalStack.setObjectName(u"bookRemovalStack")
        self.page_17 = QWidget()
        self.page_17.setObjectName(u"page_17")
        self.verticalLayout_29 = QVBoxLayout(self.page_17)
        self.verticalLayout_29.setObjectName(u"verticalLayout_29")
        self.chooseBookRemovalLabel = QLabel(self.page_17)
        self.chooseBookRemovalLabel.setObjectName(u"chooseBookRemovalLabel")
        sizePolicy9.setHeightForWidth(self.chooseBookRemovalLabel.sizePolicy().hasHeightForWidth())
        self.chooseBookRemovalLabel.setSizePolicy(sizePolicy9)
        self.chooseBookRemovalLabel.setFont(font6)
        self.chooseBookRemovalLabel.setAlignment(Qt.AlignCenter)

        self.verticalLayout_29.addWidget(self.chooseBookRemovalLabel)

        self.bookRemovalStack.addWidget(self.page_17)
        self.page_18 = QWidget()
        self.page_18.setObjectName(u"page_18")
        self.verticalLayout_31 = QVBoxLayout(self.page_18)
        self.verticalLayout_31.setObjectName(u"verticalLayout_31")
        self.verticalLayout_30 = QVBoxLayout()
        self.verticalLayout_30.setObjectName(u"verticalLayout_30")
        self.bookRemoveInfo = QLabel(self.page_18)
        self.bookRemoveInfo.setObjectName(u"bookRemoveInfo")
        sizePolicy9.setHeightForWidth(self.bookRemoveInfo.sizePolicy().hasHeightForWidth())
        self.bookRemoveInfo.setSizePolicy(sizePolicy9)
        self.bookRemoveInfo.setFont(font6)
        self.bookRemoveInfo.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.verticalLayout_30.addWidget(self.bookRemoveInfo)

        self.removeBookButton = QPushButton(self.page_18)
        self.removeBookButton.setObjectName(u"removeBookButton")
        font17 = QFont()
        font17.setFamily(u"DejaVu Sans")
        font17.setPointSize(18)
        self.removeBookButton.setFont(font17)

        self.verticalLayout_30.addWidget(self.removeBookButton)


        self.verticalLayout_31.addLayout(self.verticalLayout_30)

        self.bookRemovalStack.addWidget(self.page_18)
        self.splitter_7.addWidget(self.bookRemovalStack)

        self.horizontalLayout_3.addWidget(self.splitter_7)

        self.checkIfBooksInLibraryStack.addWidget(self.page_16)

        self.verticalLayout_26.addWidget(self.checkIfBooksInLibraryStack)


        self.verticalLayout_27.addLayout(self.verticalLayout_26)

        self.Stack.addWidget(self.librarian_remove_book_page)
        self.librarian_add_member_page = QWidget()
        self.librarian_add_member_page.setObjectName(u"librarian_add_member_page")
        self.Stack.addWidget(self.librarian_add_member_page)
        self.librarian_display_members_page = QWidget()
        self.librarian_display_members_page.setObjectName(u"librarian_display_members_page")
        self.Stack.addWidget(self.librarian_display_members_page)
        self.librarian_display_info_page = QWidget()
        self.librarian_display_info_page.setObjectName(u"librarian_display_info_page")
        self.Stack.addWidget(self.librarian_display_info_page)

        self.horizontalLayout.addWidget(self.Stack)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.Stack.setCurrentIndex(6)
        self.genreStack.setCurrentIndex(0)
        self.bookStack.setCurrentIndex(0)
        self.ifClientHasRentingStack.setCurrentIndex(0)
        self.curRentingStack.setCurrentIndex(0)
        self.calendarStack.setCurrentIndex(1)
        self.rentingHistoryStack.setCurrentIndex(1)
        self.ifClientHasNoReservationsStack.setCurrentIndex(0)
        self.reservationStack.setCurrentIndex(0)
        self.checkIfBooksInLibraryStack.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"LibApp", None))
        self.actionMain_menu.setText(QCoreApplication.translate("MainWindow", u"Main menu", None))
        self.homeLabel1.setText(QCoreApplication.translate("MainWindow", u"Welcome to LibApp", None))
        self.homeLabel2.setText(QCoreApplication.translate("MainWindow", u"Please, enter your login", None))
        self.loginLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your login here...", None))
        self.submitLoginButton.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.helloClientLabel.setText(QCoreApplication.translate("MainWindow", u"Hello!", None))
        self.clientHomeWelcomeLabel.setText(QCoreApplication.translate("MainWindow", u"Welcome to your Libapp account.", None))
        self.clientHomeQstLabel.setText(QCoreApplication.translate("MainWindow", u"What would you like to do?", None))
        self.clientModeLabel.setText(QCoreApplication.translate("MainWindow", u"Rank of account: Client", None))
        self.clientDisplayRentingsButton.setText(QCoreApplication.translate("MainWindow", u"Display current rentings", None))
        self.clientDisplayHistoryButton.setText(QCoreApplication.translate("MainWindow", u"Display my renting history", None))
        self.clientLogoutButton.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.clientDisplayBooksButton.setText(QCoreApplication.translate("MainWindow", u"Display list of books", None))
        self.clientDisplayReservationsButton.setText(QCoreApplication.translate("MainWindow", u"Display current reservations", None))
        self.mainMenuButton0.setText(QCoreApplication.translate("MainWindow", u"Main Menu", None))
        self.chooseBookLabel.setText(QCoreApplication.translate("MainWindow", u"Choose book from list", None))
        self.bookInfo.setText("")
        self.bookBorrowButton.setText(QCoreApplication.translate("MainWindow", u"Borrow book", None))
        self.reservationButton.setText(QCoreApplication.translate("MainWindow", u"Make reservation", None))
        self.chooseGenreLabel.setText(QCoreApplication.translate("MainWindow", u"Choose genre from list", None))
        self.mainMenuButton1.setText(QCoreApplication.translate("MainWindow", u"Main Menu", None))
        self.chooseRentingLabel.setText(QCoreApplication.translate("MainWindow", u"Choose renting from list", None))
        self.rentingBookInfo.setText("")
        self.rentingInfo.setText("")
        self.returnBookButton.setText(QCoreApplication.translate("MainWindow", u"Return book to library", None))
        self.renewRentingButton.setText(QCoreApplication.translate("MainWindow", u"Renew renting", None))
        self.noCurrentRentingsLabel.setText(QCoreApplication.translate("MainWindow", u"You have no active rentings.", None))
        self.mainMenuButton2.setText(QCoreApplication.translate("MainWindow", u"Main Menu", None))
        self.selectDayLabel.setText(QCoreApplication.translate("MainWindow", u"Choose day from calendar", None))
        self.rentingHistoryChooseRenting.setText(QCoreApplication.translate("MainWindow", u"Choose renting from list for info", None))
        self.rentingHistoryRentingInfo.setText("")
        self.mainMenuButton3.setText(QCoreApplication.translate("MainWindow", u"Main Menu", None))
        self.chooseReservationLabel.setText(QCoreApplication.translate("MainWindow", u"Choose reservation from list", None))
        self.reservationInfo.setText("")
        self.reservationBorrowButton.setText(QCoreApplication.translate("MainWindow", u"Borrow book", None))
        self.cancelReservationButton.setText(QCoreApplication.translate("MainWindow", u"Cancel reservation", None))
        self.noCurrentReservationsLabel.setText(QCoreApplication.translate("MainWindow", u"You have no active reservations.", None))
        self.librarianHelloLabel.setText(QCoreApplication.translate("MainWindow", u"Hello!", None))
        self.librarianWelcomeLabel.setText(QCoreApplication.translate("MainWindow", u"Welcome to your Libapp account.", None))
        self.librarianQstLabel.setText(QCoreApplication.translate("MainWindow", u"What would you like to do?", None))
        self.librarianModeLabel.setText(QCoreApplication.translate("MainWindow", u"Rank of account: Librarian", None))
        self.librarianAddBookButton.setText(QCoreApplication.translate("MainWindow", u"Add book to library", None))
        self.librarianRemoveBookButton.setText(QCoreApplication.translate("MainWindow", u"Remove book from library", None))
        self.librarianAddMemberButton.setText(QCoreApplication.translate("MainWindow", u"Add member to library", None))
        self.librarianDisplayMembersButton.setText(QCoreApplication.translate("MainWindow", u"Display list of members", None))
        self.librarianDisplayRentingsInfoButton.setText(QCoreApplication.translate("MainWindow", u"Display info about rentings", None))
        self.librarianLogoutButton.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.mainMenuButton4.setText(QCoreApplication.translate("MainWindow", u"Main menu", None))
        self.addBookTitleLabel.setText(QCoreApplication.translate("MainWindow", u"Title:", None))
        self.addBookTitleLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter title of the book...", None))
        self.addBookAuthorsLabel.setText(QCoreApplication.translate("MainWindow", u"Authors:", None))
        self.addBookAuthorsLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter authors of the book...", None))
        self.addBookGenreLabel.setText(QCoreApplication.translate("MainWindow", u"Genre:", None))
        self.addBookGenreLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter genre of the book...", None))
        self.addBookIdLabel.setText(QCoreApplication.translate("MainWindow", u"Id:", None))
        self.addBookIdLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter id of the book...", None))
        self.addBookButton.setText(QCoreApplication.translate("MainWindow", u"Add book to library", None))
        self.mainMenuButton5.setText(QCoreApplication.translate("MainWindow", u"Main Menu", None))
        self.checkIfBookInLibraryLabel.setText(QCoreApplication.translate("MainWindow", u"There are currently no books in library", None))
        self.chooseBookRemovalLabel.setText(QCoreApplication.translate("MainWindow", u"Choose book from list", None))
        self.bookRemoveInfo.setText("")
        self.removeBookButton.setText(QCoreApplication.translate("MainWindow", u"Remove book from library", None))
    # retranslateUi

